name: Deploy Github Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Install Trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: 'latest'

      - name: Install WASM Bindgen
        uses: jetli/wasm-bindgen-action@v0.2.0
        with:
          version: 'latest'

      - run: cp -r data/models/ web_ui/static/models
      - run: cd web_ui && trunk build --release --public-url /${{ github.event.repository.name }}/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'web_ui/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
